# Generated by Django 3.0.7 on 2020-06-15 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200615_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
